services:
  - type: web
    name: insurance-claim-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/ui/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: false
      - key: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
        value: false
